name: Laravel Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - run: composer install --no-interaction

      - run: cp .env.example .env

      - run: php artisan key:generate

      - run: php artisan test
